#version: '3'

services:
  db:
    image: postgres:13
    container_name: postgres-database-new
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: public
    networks:
      - pg-network
    ports:
      - "5432:5432"  # Expose PostgreSQL port

  dbt:
    image: dbt-postgres-image
    container_name: dbt-container
    environment:
      DBT_TARGET: dev
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4:latest  # Official pgAdmin image
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Default pgAdmin login email
      PGADMIN_DEFAULT_PASSWORD: root  # Default pgAdmin login password
    ports:
      - "8080:80"  # Expose pgAdmin's web interface on port 5050
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge
